const BADGES_DATABASE = [
    { id: 1, name: "Exact Nice", emoji: "😏", criteria: "Exactly 69", tier: "Mythic", ep: 100000 },
    { id: 2, name: "Exact Jackpot", emoji: "💰", criteria: "Exactly 777", tier: "Mythic", ep: 100000 },
    { id: 3, name: "Jackpot Six", emoji: "🏦", criteria: "Contains six 7s in a row", tier: "Mythic", ep: 100000 },
    { id: 4, name: "Exact Botanist", emoji: "🌿", criteria: "Exactly 420", tier: "Mythic", ep: 100000 },
    { id: 5, name: "Exact Devil", emoji: "😈", criteria: "Exactly 666", tier: "Mythic", ep: 100000 },
    { id: 6, name: "Exact Leet", emoji: "💻", criteria: "Exactly 1337", tier: "Mythic", ep: 100000 },
    { id: 7, name: "Exact Hell", emoji: "👹", criteria: "Exactly 7734", tier: "Mythic", ep: 100000 },
    { id: 8, name: "Exact 80085", emoji: "💎", criteria: "Exactly 80085", tier: "Mythic", ep: 100000 },
    { id: 9, name: "Exact Meaning", emoji: "🌌", criteria: "Exactly 42", tier: "Mythic", ep: 100000 },
    { id: 10, name: "Exact Emergency", emoji: "🚑", criteria: "Exactly 911", tier: "Mythic", ep: 100000 },
    { id: 11, name: "Very Very Nice", emoji: "😏", criteria: "Exactly 696969", tier: "Mythic", ep: 100000 },
    { id: 12, name: "Hotbox", emoji: "🌿", criteria: "Exactly 420420", tier: "Mythic", ep: 100000 },
    { id: 13, name: "Mayday", emoji: "🚑", criteria: "Exactly 911911", tier: "Mythic", ep: 100000 },
    { id: 14, name: "Universal Answer", emoji: "🌌", criteria: "Exactly 424242", tier: "Mythic", ep: 100000 },
    { id: 15, name: "Orwellian", emoji: "👁️", criteria: "Exactly 1984", tier: "Mythic", ep: 100000 },
    { id: 16, name: "Zero", emoji: "0️⃣", criteria: "The number zero", tier: "Mythic", ep: 100000 },
    { id: 17, name: "One", emoji: "1️⃣", criteria: "The number one", tier: "Mythic", ep: 100000 },
    { id: 18, name: "Two", emoji: "2️⃣", criteria: "The number two", tier: "Mythic", ep: 100000 },
    { id: 19, name: "Three", emoji: "3️⃣", criteria: "The number three", tier: "Mythic", ep: 100000 },
    { id: 20, name: "Four", emoji: "4️⃣", criteria: "The number four", tier: "Mythic", ep: 100000 },
    { id: 21, name: "Five", emoji: "5️⃣", criteria: "The number five", tier: "Mythic", ep: 100000 },
    { id: 22, name: "Six", emoji: "6️⃣", criteria: "The number six", tier: "Mythic", ep: 100000 },
    { id: 23, name: "Seven", emoji: "7️⃣", criteria: "The number seven", tier: "Mythic", ep: 100000 },
    { id: 24, name: "Eight", emoji: "8️⃣", criteria: "The number eight", tier: "Mythic", ep: 100000 },
    { id: 25, name: "Nine", emoji: "9️⃣", criteria: "The number nine", tier: "Mythic", ep: 100000 },
    { id: 26, name: "Exact Tree Fiddy", emoji: "🦕", criteria: "Exactly 350", tier: "Mythic", ep: 100000 },
    { id: 27, name: "Exact Six-Seven", emoji: "🫠", criteria: "Exactly 67", tier: "Mythic", ep: 100000 },
    { id: 28, name: "Exact Eighty-Six", emoji: "🍽️", criteria: "Exactly 86", tier: "Mythic", ep: 100000 },
    { id: 29, name: "Exact Orientation", emoji: "🧭", criteria: "Exactly 101", tier: "Mythic", ep: 100000 },
    { id: 30, name: "Exact Calendar", emoji: "📅", criteria: "Exactly 365", tier: "Mythic", ep: 100000 },
    { id: 31, name: "Brainrot", emoji: "🫠", criteria: "Exactly 676767", tier: "Mythic", ep: 100000 },
    { id: 32, name: "Groundhog Day", emoji: "📅", criteria: "Exactly 365365", tier: "Mythic", ep: 100000 },
    { id: 33, name: "Exact Boob", emoji: "🍈", criteria: "Exactly 8008 or 58008", tier: "Mythic", ep: 50000 },
    { id: 34, name: "13th Power", emoji: "💀", criteria: "A perfect 13th power (n¹³)", tier: "Mythic", ep: 33333 },
    { id: 35, name: "17th Power", emoji: "🧙", criteria: "A perfect 17th power (n¹⁷)", tier: "Mythic", ep: 33333 },
    { id: 36, name: "19th Power", emoji: "🌑", criteria: "A perfect 19th power (n¹⁹)", tier: "Mythic", ep: 33333 },
    { id: 37, name: "10th Power", emoji: "🔟", criteria: "A perfect 10th power (n¹⁰)", tier: "Mythic", ep: 25000 },
    { id: 38, name: "11th Power", emoji: "🕚", criteria: "A perfect 11th power (n¹¹)", tier: "Mythic", ep: 25000 },
    { id: 39, name: "Pi", emoji: "🥧", criteria: "Exactly π (314, 3141, 31415, or 314159)", tier: "Mythic", ep: 25000 },
    { id: 40, name: "Euler's Number", emoji: "📈", criteria: "The number e (271, 2718, 27182, or 271828)", tier: "Mythic", ep: 25000 },
    { id: 41, name: "4 Consecutive Numbers", emoji: "⛓️", criteria: "The entire number splits into four consecutive integers in order", tier: "Mythic", ep: 25000 },
    { id: 42, name: "9th Power", emoji: "☁️", criteria: "A perfect 9th power (n⁹)", tier: "Mythic", ep: 20000 },
    { id: 43, name: "8th Power", emoji: "🎱", criteria: "A perfect 8th power (n⁸)", tier: "Mythic", ep: 16666 },
    { id: 44, name: "7th Power", emoji: "🌈", criteria: "A perfect 7th power (n⁷)", tier: "Mythic", ep: 12500 },
    { id: 45, name: "Factorial", emoji: "❗", criteria: "A factorial number (n!)", tier: "Mythic", ep: 11111 },
    { id: 46, name: "Hello", emoji: "👋", criteria: "Contains 07734 (spells HELLO upside-down)", tier: "Mythic", ep: 11111 },
    { id: 47, name: "Sequence (6)", emoji: "🔢", criteria: "Contains a sequence of 6 consecutive digits", tier: "Mythic", ep: 11111 },
    { id: 48, name: "Contiguous Sixes", emoji: "➖➖➖➖", criteria: "Six identical consecutive digits", tier: "Mythic", ep: 10000 },
    { id: 49, name: "Deep Void (5)", emoji: "⚫", criteria: "Contains 00000", tier: "Mythic", ep: 10000 },
    { id: 50, name: "Single Digit", emoji: "☝️", criteria: "Has exactly one digit", tier: "Mythic", ep: 10000 },
    { id: 51, name: "Quint Nine", emoji: "🥳", criteria: "Ends in 99999", tier: "Mythic", ep: 10000 },
    { id: 52, name: "6th Power", emoji: "🎲", criteria: "A perfect 6th power (n⁶)", tier: "Anomaly", ep: 9090 },
    { id: 53, name: "Power of Three", emoji: "🔺", criteria: "A power of 3 (3ⁿ)", tier: "Anomaly", ep: 7692 },
    { id: 54, name: "5th Power", emoji: "🖐️", criteria: "A perfect 5th power (n⁵)", tier: "Anomaly", ep: 6250 },
    { id: 55, name: "Jackpot Five", emoji: "💰💰💰", criteria: "Contains five 7s in a row", tier: "Anomaly", ep: 5263 },
    { id: 56, name: "Power of Two", emoji: "💾", criteria: "A power of 2 (2ⁿ)", tier: "Anomaly", ep: 5000 },
    { id: 57, name: "Royal Flush", emoji: "👑", criteria: "Contains 56789 — the highest possible straight", tier: "Anomaly", ep: 5000 },
    { id: 58, name: "58008", emoji: "🔠", criteria: "Contains 58008 (spells BOOBS upside-down)", tier: "Anomaly", ep: 5000 },
    { id: 59, name: "80085", emoji: "🅱️", criteria: "Contains 80085 (spells BOOBS)", tier: "Anomaly", ep: 5000 },
    { id: 60, name: "Pi Slice (5)", emoji: "🥧", criteria: "Contains 31415", tier: "Anomaly", ep: 5000 },
    { id: 61, name: "E Slice (5)", emoji: "📈", criteria: "Contains 27182", tier: "Anomaly", ep: 5000 },
    { id: 62, name: "Cascade", emoji: "🌊", criteria: "Every digit increases by exactly 1 from the previous", tier: "Anomaly", ep: 3333 },
    { id: 63, name: "Fibonacci Number", emoji: "🐚", criteria: "Part of the golden ratio sequence found in nature", tier: "Anomaly", ep: 3333 },
    { id: 64, name: "4th Power", emoji: "📦", criteria: "A perfect fourth power (n⁴)", tier: "Anomaly", ep: 3125 },
    { id: 65, name: "Waterfall", emoji: "🚿", criteria: "Every digit decreases by exactly 1 from the previous", tier: "Anomaly", ep: 2857 },
    { id: 66, name: "4 Consecutive Numbers (Contains)", emoji: "🔗", criteria: "Contains four adjacent consecutive integers", tier: "Anomaly", ep: 2631 },
    { id: 67, name: "4 Consecutive Numbers (Scrambled)", emoji: "🔀", criteria: "The entire number splits into four consecutive integers, but not in order", tier: "Anomaly", ep: 2272 },
    { id: 68, name: "Homogeneous", emoji: "🥛", criteria: "All digits are the same", tier: "Anomaly", ep: 2222 },
    { id: 69, name: "Binary Soul", emoji: "🤖", criteria: "Only 0s and 1s", tier: "Anomaly", ep: 1538 },
    { id: 70, name: "Straight Flush", emoji: "🃏", criteria: "Contains 5 consecutive same-parity digits (02468, 13579, or reverse)", tier: "Anomaly", ep: 1449 },
    { id: 71, name: "Two Digits", emoji: "✌️", criteria: "Has exactly two digits", tier: "Anomaly", ep: 1111 },
    { id: 72, name: "Spy Number", emoji: "🕵️", criteria: "The sum of its digits equals the product of its digits", tier: "Anomaly", ep: 1030 },
    { id: 73, name: "Quad Nine", emoji: "🎊", criteria: "Ends in 9999", tier: "Anomaly", ep: 1000 },
    { id: 74, name: "Semi-Epoch", emoji: "🗿", criteria: "Ends in 5000", tier: "Anomaly", ep: 1000 },
    { id: 75, name: "3rd Power", emoji: "🧊", criteria: "A perfect cube (n³)", tier: "Anomaly", ep: 990 },
    { id: 76, name: "Even Spacing", emoji: "📏", criteria: "All digits are evenly spaced in an arithmetic sequence", tier: "Anomaly", ep: 862 },
    { id: 77, name: "3 Consecutive Numbers", emoji: "⛓️", criteria: "The entire number splits into three consecutive integers in order", tier: "Epic", ep: 555 },
    { id: 78, name: "Contiguous Fives", emoji: "➖➖➖", criteria: "Five identical consecutive digits", tier: "Epic", ep: 552 },
    { id: 79, name: "Deep Void (4)", emoji: "🌌", criteria: "Contains 0000", tier: "Epic", ep: 552 },
    { id: 80, name: "Strobogrammatic", emoji: "🙃", criteria: "Looks the same when rotated 180 degrees", tier: "Epic", ep: 502 },
    { id: 81, name: "Straight", emoji: "📏", criteria: "Contains a sequence of 5 consecutive digits (ascending or descending)", tier: "Epic", ep: 454 },
    { id: 82, name: "Jackpot Four", emoji: "💰💰", criteria: "Contains four 7s in a row", tier: "Epic", ep: 357 },
    { id: 83, name: "Very Nice", emoji: "🥵", criteria: "Contains 6969", tier: "Epic", ep: 334 },
    { id: 84, name: "Deeper Meaning", emoji: "🌌", criteria: "Contains 4242", tier: "Epic", ep: 334 },
    { id: 85, name: "6767", emoji: "🫠", criteria: "Contains 6767", tier: "Epic", ep: 334 },
    { id: 86, name: "Leet", emoji: "💻", criteria: "Contains 1337", tier: "Epic", ep: 333 },
    { id: 87, name: "Hell", emoji: "🔥", criteria: "Contains 7734 (spells HELL upside-down)", tier: "Epic", ep: 333 },
    { id: 88, name: "8008", emoji: "🔢", criteria: "Contains 8008 (spells BOOB upside-down)", tier: "Epic", ep: 333 },
    { id: 89, name: "Big Brother", emoji: "👁️", criteria: "Contains 1984", tier: "Epic", ep: 333 },
    { id: 90, name: "Pi Slice (4)", emoji: "🥧", criteria: "Contains 3141", tier: "Epic", ep: 333 },
    { id: 91, name: "E Slice (4)", emoji: "📈", criteria: "Contains 2718", tier: "Epic", ep: 333 },
    { id: 92, name: "3 Consecutive Numbers (Scrambled)", emoji: "🔀", criteria: "The entire number splits into three consecutive integers, but not in order", tier: "Epic", ep: 277 },
    { id: 93, name: "Zipper", emoji: "🤐", criteria: "Two digits alternating perfectly", tier: "Epic", ep: 246 },
    { id: 94, name: "Ascension", emoji: "📈", criteria: "Every digit is strictly larger than the previous", tier: "Epic", ep: 219 },
    { id: 95, name: "3 Consecutive Numbers (Contains)", emoji: "🔗", criteria: "Contains three adjacent consecutive integers", tier: "Epic", ep: 157 },
    { id: 96, name: "Contiguous Three Pair", emoji: "👨‍👩‍👧‍👦", criteria: "Contains three adjacent contiguous pairs", tier: "Epic", ep: 154 },
    { id: 97, name: "Framed Pair", emoji: "🖼️", criteria: "A 4-digit number where the middle two digits match each other but differ from both end digits", tier: "Epic", ep: 137 },
    { id: 98, name: "Framed Triple", emoji: "🖼️", criteria: "A triple in the middle, bookended by different digits", tier: "Epic", ep: 137 },
    { id: 99, name: "Decay", emoji: "📉", criteria: "Every digit is strictly smaller than the previous", tier: "Epic", ep: 119 },
    { id: 100, name: "Three Digits", emoji: "🤟", criteria: "Has exactly three digits", tier: "Epic", ep: 111 },
    { id: 101, name: "Echo", emoji: "📣", criteria: "The first half repeats as the second half", tier: "Epic", ep: 100 },
    { id: 102, name: "Millennium", emoji: "🗓️", criteria: "Ends in triple zeros", tier: "Epic", ep: 100 },
    { id: 103, name: "Pronic Number", emoji: "🧮", criteria: "The product of two consecutive integers (n * (n+1))", tier: "Epic", ep: 100 },
    { id: 104, name: "Triple Nine", emoji: "🎉", criteria: "Ends in 999", tier: "Epic", ep: 100 },
    { id: 105, name: "Semi-Millennium", emoji: "📜", criteria: "Ends in 500", tier: "Epic", ep: 100 },
    { id: 106, name: "Colossal", emoji: "🪨", criteria: "A number greater than 999,000", tier: "Epic", ep: 100 },
    { id: 107, name: "2nd Power", emoji: "🟦", criteria: "A perfect square (n²)", tier: "Epic", ep: 99 },
    { id: 108, name: "Even Spacing (Absolute)", emoji: "📐", criteria: "All digits have the same absolute spacing (e.g., ±2 each time)", tier: "Epic", ep: 90 },
    { id: 109, name: "Firefly", emoji: "🪲", criteria: "One unique digit among identical others", tier: "Epic", ep: 82 },
    { id: 110, name: "2 Consecutive Numbers", emoji: "🔗", criteria: "The entire number splits into two consecutive integers", tier: "Epic", ep: 50 },
    { id: 111, name: "Palindrome", emoji: "🪞", criteria: "Reads the same forwards and backwards", tier: "Epic", ep: 50 },
    { id: 112, name: "Contiguous Quads", emoji: "➖➖", criteria: "Four identical consecutive digits", tier: "Rare", ep: 37 },
    { id: 113, name: "Deep Void (3)", emoji: "🌑", criteria: "Contains 000", tier: "Rare", ep: 37 },
    { id: 114, name: "Turtle", emoji: "🐢", criteria: "All consecutive digits differ by at most 1", tier: "Rare", ep: 36 },
    { id: 115, name: "Secret Agent", emoji: "🕶️", criteria: "Contains 007", tier: "Rare", ep: 34 },
    { id: 116, name: "Heavy", emoji: "🧱", criteria: "The sum of its digits exceeds 45", tier: "Rare", ep: 33 },
    { id: 117, name: "Contiguous Full House", emoji: "🏰", criteria: "Contains a contiguous set of three adjacent to a contiguous set of two", tier: "Rare", ep: 30 },
    { id: 118, name: "Jackpot", emoji: "💰", criteria: "Contains 777", tier: "Rare", ep: 27 },
    { id: 119, name: "Devil", emoji: "😈", criteria: "Contains 666", tier: "Rare", ep: 27 },
    { id: 120, name: "Sequence (4)", emoji: "🔢", criteria: "Contains a sequence of 4 consecutive digits", tier: "Rare", ep: 25 },
    { id: 121, name: "Error 404", emoji: "🚫", criteria: "Contains 404", tier: "Rare", ep: 25 },
    { id: 122, name: "Orientation", emoji: "🧭", criteria: "Contains 101", tier: "Rare", ep: 25 },
    { id: 123, name: "Botanist", emoji: "🌿", criteria: "Contains 420", tier: "Rare", ep: 25 },
    { id: 124, name: "Emergency", emoji: "🚑", criteria: "Contains 911", tier: "Rare", ep: 25 },
    { id: 125, name: "Pi Slice (3)", emoji: "🥧", criteria: "Contains 314", tier: "Rare", ep: 25 },
    { id: 126, name: "E Slice (3)", emoji: "📈", criteria: "Contains 271", tier: "Rare", ep: 25 },
    { id: 127, name: "Tree Fiddy", emoji: "🦕", criteria: "Contains 350", tier: "Rare", ep: 25 },
    { id: 128, name: "Calendar", emoji: "📅", criteria: "Contains 365", tier: "Rare", ep: 25 },
    { id: 129, name: "Divisible by Three", emoji: "🔺", criteria: "Every digit is divisible by 3", tier: "Rare", ep: 24 },
    { id: 130, name: "Scramble", emoji: "🔀", criteria: "All digits form a consecutive sequence when sorted", tier: "Rare", ep: 22 },
    { id: 131, name: "Duality", emoji: "☯️", criteria: "Uses exactly two different digits", tier: "Rare", ep: 21 },
    { id: 132, name: "Framed Double", emoji: "🖼️", criteria: "Two pairs in the middle, bookended by different digits", tier: "Rare", ep: 15 },
    { id: 133, name: "Paired Bookends", emoji: "👐", criteria: "Starts with a pair and ends with a different pair", tier: "Rare", ep: 11 },
    { id: 134, name: "Four Digits", emoji: "🍀", criteria: "Has exactly four digits", tier: "Rare", ep: 11 },
    { id: 135, name: "Three Pair", emoji: "  ", criteria: "Contains three distinct pairs of matching digits", tier: "Rare", ep: 10 },
    { id: 136, name: "Bookends", emoji: "📚", criteria: "The first two digits match the last two", tier: "Rare", ep: 10 },
    { id: 137, name: "Mirror Bookends", emoji: "📖", criteria: "First two digits are reversed as the last two", tier: "Rare", ep: 10 },
    { id: 138, name: "Century", emoji: "💯", criteria: "Ends in double zeros", tier: "Rare", ep: 10 },
    { id: 139, name: "Double Nine", emoji: "🎈", criteria: "Ends in 99", tier: "Rare", ep: 10 },
    { id: 140, name: "Semi-Century", emoji: "🗓️", criteria: "Ends in 50", tier: "Rare", ep: 10 },
    { id: 141, name: "Four of a Kind", emoji: "🍀", criteria: "Contains four identical digits", tier: "Uncommon", ep: 8 },
    { id: 142, name: "Low Ball", emoji: "📉", criteria: "Contains only digits from 0 to 4", tier: "Uncommon", ep: 6 },
    { id: 143, name: "Contiguous Two Pair", emoji: "👨‍👩‍👧‍👦", criteria: "Contains two adjacent contiguous pairs", tier: "Uncommon", ep: 6 },
    { id: 144, name: "Mountain", emoji: "🏔️", criteria: "Digits ascend to a peak and then descend", tier: "Uncommon", ep: 5 },
    { id: 145, name: "Double Hop", emoji: "🦘", criteria: "A digit appears at every other position (3 times)", tier: "Uncommon", ep: 5 },
    { id: 146, name: "High Roller", emoji: "🤑", criteria: "Contains only digits from 5 to 9", tier: "Uncommon", ep: 5 },
    { id: 147, name: "Valley", emoji: "🏜️", criteria: "Digits descend to a trough and then ascend", tier: "Uncommon", ep: 4 },
    { id: 148, name: "Mini Echo", emoji: "🔂", criteria: "Contains an adjacent 2-digit repeat", tier: "Uncommon", ep: 3 },
    { id: 149, name: "Alternator", emoji: "⚡", criteria: "Digits strictly alternate between even and odd", tier: "Uncommon", ep: 2 },
    { id: 150, name: "Flush", emoji: "🎨", criteria: "All digits are either all even or all odd", tier: "Uncommon", ep: 2 },
    { id: 151, name: "Contiguous Trips", emoji: "➖", criteria: "Three identical consecutive digits", tier: "Uncommon", ep: 2 },
    { id: 152, name: "Deep Void", emoji: "🕳️", criteria: "Contains 00", tier: "Uncommon", ep: 2 },
    { id: 153, name: "Feather", emoji: "🪶", criteria: "The sum of its digits is less than 15", tier: "Uncommon", ep: 2 },
    { id: 154, name: "Blackjack", emoji: "♠️", criteria: "Digits sum exactly to 21", tier: "Uncommon", ep: 2 },
    { id: 155, name: "Full House", emoji: "🏠", criteria: "Contains a set of three and a set of two", tier: "Uncommon", ep: 2 },
    { id: 156, name: "Snake Eyes", emoji: "🎲", criteria: "Contains a single pair of ones and no other pairs", tier: "Uncommon", ep: 2 },
    { id: 157, name: "Nice", emoji: "😏", criteria: "Contains the number 69", tier: "Uncommon", ep: 2 },
    { id: 158, name: "Meaning of Life", emoji: "🌌", criteria: "Contains 42", tier: "Uncommon", ep: 2 },
    { id: 159, name: "Six-Seven", emoji: "🫠", criteria: "Contains 67", tier: "Uncommon", ep: 2 },
    { id: 160, name: "Eighty-Six", emoji: "🍽️", criteria: "Contains 86", tier: "Uncommon", ep: 2 },
    { id: 161, name: "Balanced", emoji: "⚖️", criteria: "Sum of first half of digits equals sum of second half", tier: "Uncommon", ep: 1 },
    { id: 162, name: "Rhyme", emoji: "🎶", criteria: "Contains the same 2+ digit substring twice", tier: "Uncommon", ep: 1 },
    { id: 163, name: "Sequence (3)", emoji: "🔢", criteria: "Contains a sequence of 3 consecutive digits", tier: "Uncommon", ep: 1 },
    { id: 164, name: "2 Consecutive Numbers (Contains)", emoji: "🔗", criteria: "Contains two adjacent substrings that are consecutive integers", tier: "Uncommon", ep: 1 },
    { id: 165, name: "2 Consecutive Numbers (Nearby)", emoji: "🔗", criteria: "Contains two non-adjacent substrings that are consecutive integers", tier: "Uncommon", ep: 1 },
    { id: 166, name: "Prime Number", emoji: "💎", criteria: "Divisible only by 1 and itself", tier: "Uncommon", ep: 1 },
    { id: 167, name: "Trinity", emoji: "⚜️", criteria: "Uses exactly three different digits", tier: "Uncommon", ep: 1 },
    { id: 168, name: "Dozen", emoji: "🍩", criteria: "Divisible by 12", tier: "Uncommon", ep: 1 },
    { id: 169, name: "Five Digits", emoji: "🖐️", criteria: "Has exactly five digits", tier: "Uncommon", ep: 1 },
    { id: 170, name: "Eleven", emoji: "🕚", criteria: "Divisible by 11", tier: "Uncommon", ep: 1 },
    { id: 171, name: "Harshad Number", emoji: "🤝", criteria: "Divisible by the sum of its own digits", tier: "Uncommon", ep: 1 },
    { id: 172, name: "Clean", emoji: "🧼", criteria: "Ends in a zero", tier: "Uncommon", ep: 1 },
    { id: 173, name: "Semi-Clean", emoji: "🧹", criteria: "Ends in a 5", tier: "Uncommon", ep: 1 },
    { id: 174, name: "Equilibrium", emoji: "🧘", criteria: "The first and last digits are identical", tier: "Uncommon", ep: 1 },
    { id: 175, name: "Sandwich", emoji: "🥪", criteria: "A different number between two indentical numbers.", tier: "Uncommon", ep: 1 },
    { id: 176, name: "Hills", emoji: "🏞️", criteria: "Digits strictly alternate between rising and falling", tier: "Common", ep: 1 },
    { id: 177, name: "Three of a Kind", emoji: "🎰", criteria: "Contains three identical digits", tier: "Common", ep: 1 },
    { id: 178, name: "Lucky Seven (Divisible)", emoji: "🎰", criteria: "Divisible by 7", tier: "Common", ep: 1 },
    { id: 179, name: "Heterogeneous", emoji: "🥗", criteria: "No repeated digits", tier: "Common", ep: 1 },
    { id: 180, name: "Gap One", emoji: "↕️", criteria: "The first and last digits differ by exactly 1", tier: "Common", ep: 1 },
    { id: 181, name: "Two Pair", emoji: "2️⃣", criteria: "Contains two distinct pairs of matching digits", tier: "Common", ep: 1 },
    { id: 182, name: "Hopscotch", emoji: "🦘", criteria: "A digit appears at every other position (2 times)", tier: "Common", ep: 1 },
    { id: 183, name: "Ghost", emoji: "👻", criteria: "Contains exactly one 0", tier: "Common", ep: 1 },
    { id: 184, name: "Quartet", emoji: "🎻", criteria: "Uses exactly four different digits", tier: "Common", ep: 1 },
    { id: 185, name: "Hydrogen (1)", emoji: "💧", criteria: "Contains exactly one 1", tier: "Common", ep: 1 },
    { id: 186, name: "Helium (2)", emoji: "🎈", criteria: "Contains exactly one 2", tier: "Common", ep: 1 },
    { id: 187, name: "Carbon (6)", emoji: "✏️", criteria: "Contains exactly one 6", tier: "Common", ep: 1 },
    { id: 188, name: "Oxygen (8)", emoji: "💨", criteria: "Contains exactly one 8", tier: "Common", ep: 1 },
    { id: 189, name: "Lithium (3)", emoji: "🔋", criteria: "Contains exactly one 3", tier: "Common", ep: 1 },
    { id: 190, name: "Beryllium (4)", emoji: "💎", criteria: "Contains exactly one 4", tier: "Common", ep: 1 },
    { id: 191, name: "Boron (5)", emoji: "🧼", criteria: "Contains exactly one 5", tier: "Common", ep: 1 },
    { id: 192, name: "Nitrogen (7)", emoji: "❄️", criteria: "Contains exactly one 7", tier: "Common", ep: 1 },
    { id: 193, name: "Fluorine (9)", emoji: "🦷", criteria: "Contains exactly one 9", tier: "Common", ep: 1 },
    { id: 194, name: "Grounded", emoji: "⚓", criteria: "The first digit is smaller than the last", tier: "Common", ep: 1 },
    { id: 195, name: "Contiguous Pair", emoji: "🫂", criteria: "Contains a contiguous pair of matching digits", tier: "Common", ep: 1 },
    { id: 196, name: "Lucky Seven", emoji: "7️⃣", criteria: "Contains the number 7", tier: "Common", ep: 1 },
    { id: 197, name: "Even", emoji: "⚖️", criteria: "Divisible by 2", tier: "Common", ep: 1 },
    { id: 198, name: "Odd", emoji: "🦄", criteria: "Not divisible by 2", tier: "Common", ep: 1 },
    { id: 199, name: "Liftoff", emoji: "🚀", criteria: "The first digit is larger than the last", tier: "Common", ep: 1 },
    { id: 200, name: "Void", emoji: "🕳️", criteria: "Contains no zeros", tier: "Common", ep: 1 },
    { id: 201, name: "Neighbors", emoji: "🏘️", criteria: "Contains two digits that are adjacent in value", tier: "Common", ep: 1 },
    { id: 202, name: "Pair", emoji: "👯", criteria: "Contains a pair of matching digits", tier: "Common", ep: 1 },
    { id: 203, name: "Six Digits", emoji: "🐝", criteria: "Has exactly six digits", tier: "Common", ep: 1 },
    { id: 204, name: "Leet", emoji: "💻", criteria: "Contains the elite signature 1337", tier: "Epic", ep: 333 },
    { id: 205, name: "Not Funny", emoji: "😑", criteria: "Contains the awkward number 67", tier: "Uncommon", ep: 2 },
    { id: 206, name: "The Devil's Area Code", emoji: "🔥", criteria: "Contains 666 anywhere inside it", tier: "Rare", ep: 27 },
    { id: 207, name: "High Five", emoji: "✋", criteria: "Contains five identical numbers split or contiguous", tier: "Epic", ep: 552 },
    { id: 208, name: "Binary Mirage", emoji: "🔮", criteria: "Contains only 0s, 1s, or 8s", tier: "Anomaly", ep: 1538 },
    { id: 209, name: "Echo", emoji: "🗣️", criteria: "The first half of the number perfectly matches the second half", tier: "Rare", ep: 4500 },
    { id: 210, name: "Bookends", emoji: "📚", criteria: "The first two digits exactly match the last two digits.", tier: "Rare", ep: 3800 },
    { id: 211, name: "Sandwich", emoji: "🥪", criteria: "A digit is perfectly squeezed between two identical digits", tier: "Uncommon", ep: 1500 },
    { id: 212, name: "Century", emoji: "💯", criteria: "The roll ends in a clean double zero.", tier: "Common", ep: 300 },
    { id: 213, name: "Millennium", emoji: "🎆", criteria: "The roll ends in a clean triple zero.", tier: "Uncommon", ep: 1800 },
    { id: 214, name: "Perfect Square", emoji: "📐", criteria: "The entire number evaluates to a perfect square root.", tier: "Epic", ep: 12000 },
    { id: 215, name: "Perfect Cube", emoji: "🧊", criteria: "The entire number evaluates to a perfect cube root.", tier: "Anomaly", ep: 42000 },
    { id: 216, name: "HTTP 404", emoji: "🚫", criteria: "Contains the classic 404 Not Found error code.", tier: "Uncommon", ep: 1100 },
    { id: 217, name: "HTTP 200", emoji: "✅", criteria: "Contains the HTTP OK 200 status code.", tier: "Uncommon", ep: 1100 },
    { id: 218, name: "Area 51", emoji: "👽", criteria: "Contains the classified number 51.", tier: "Common", ep: 450 }
];